foreground              #e6f9fc
background              #152d36
selection_foreground    #040a0c
selection_background    #f9e2af

cursor                  #42c8d9
cursor_text_color       #040a0c

url_color               #89dceb

active_border_color     #42c8d9
inactive_border_color   #20424f
bell_border_color       #b4befe

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #040a0c
active_tab_background   #5cc2e0
inactive_tab_foreground #a0dbe6
inactive_tab_background #152d36
tab_bar_background      #040a0c

mark1_foreground #040a0c
mark1_background #42c8d9
mark2_foreground #040a0c
mark2_background #94e2d5
mark3_foreground #040a0c
mark3_background #89dceb

color0 #20424f
color8 #c4eff7

color1 #b4befe
color9 #cba6f7

color2  #42c8d9
color10 #5cc2e0

color3  #89dceb
color11 #f5c2e7

color4  #94e2d5
color12 #f9e2af

color5  #5cc2e0
color13 #cba6f7

color6  #f9e2af
color14 #f5c2e7

color7  #a0dbe6
color15 #e6f9fc
