
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@75",
    position = "0x0",
    scale    = "1",
})

hl.config({
    cursor = {
        -- Отключаем аппаратные курсоры NVIDIA
        no_hardware_cursors = true,
        -- Принудительно рендерим мышь через CPU-буфер (убирает невидимость)
        use_cpu_buffer = true,
    },
})
---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "hyprlauncher"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  ◈ AUTOSTART (AUTOGENERATED FROM SETTINGS.JSON)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
hl.on("hyprland.start", function ()
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("~/.config/hypr/scripts/init.sh")
    hl.exec_cmd("~/.config/hypr/scripts/settings_watcher.sh")
    hl.exec_cmd("playerctld")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("~/.config/hypr/scripts/volume_listener.sh")
    hl.exec_cmd("~/.config/hypr/scripts/update_notifier.sh")
    hl.exec_cmd("hyprctl setcursor Moga-Black 24")
    -- Запуск новой Noctalia v5 вместо старого Quickshell, SwayOSD и Awww
    hl.exec_cmd("noctalia")
end)



-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

----------------------------------------------------------------------------------------
---- ENVIRONMENT VARIABLES (AUTOGENERATED) ---------------------------------------------
----------------------------------------------------------------------------------------

-- Базовые пути и окружение
hl.env("NIXOS_OZONE_WL", "1")
hl.env("XDG_PICTURES_DIR", "/home/camelcase/Pictures")
hl.env("XDG_VIDEOS_DIR", "/home/camelcase/Videos")
hl.env("WALLPAPER_DIR", "/home/camelcase/Pictures/Wallpapers")
hl.env("SCRIPT_DIR", "/home/camelcase/.config/hypr/scripts")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- Hardware Injections (Оптимизация NVIDIA)
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("__NV_PRIME_RENDER_OFFLOAD", "1")
hl.env("__NV_PRIME_RENDER_OFFLOAD_PROVIDER", "NVIDIA-G0")
hl.env("__GL_GSYNC_ALLOWED", "0")
hl.env("__GL_VRR_ALLOWED", "0")
hl.env("__GL_SHADER_DISK_CACHE", "1")
hl.env("__GL_SHADER_DISK_CACHE_PATH", "/home/camelcase/.cache/nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("LIBVA_DRIVER_NAME", "nvidia")

-- Базовые переменные для XWayland, курсора и GTK
hl.env("XCURSOR_THEME", "Moga-Black")
hl.env("XCURSOR_SIZE", "24")

-- Отключаем принудительный hyprcursor, чтобы система корректно откатилась на XCursor
hl.env("HYPRCURSOR_THEME", "")
hl.env("HYPRCURSOR_SIZE", "")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


----------------------------------------------------------------------------------------
---- LOOK AND FEEL (MERGED NATIVE LUA CONFIG) -------------------------------------------
----------------------------------------------------------------------------------------

hl.config({
    -- ───────── Базовые настройки окон (General) ─────────
    general = {
        border_size             = 2,
        gaps_in                 = 5,
        gaps_out                = 6,
        float_gaps              = 6,
        resize_on_border        = true,
        extend_border_grab_area = 30,
        allow_tearing           = false,
        layout                  = "dwindle",

        -- Цвета рамок (Перевод $active_border в нативный градиент)
        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },

    -- ───────── Эффекты декораций (Decoration) ─────────
decoration = {
        rounding         = 13,
        rounding_power   = 2,
        active_opacity   = 1.0,
        inactive_opacity = 0.9,
	fullscreen_opacity = 0.85,
        shadow = {
            enabled = false,
        },

        -- Настройки размытия (Blur) с добавлением новых параметров
        blur = {
            enabled           = true,
            size              = 8,
            passes            = 3,
            new_optimizations = true,
            vibrancy          = 0.1696,
            xray              = true,  -- Просвечивание сквозь окна под прозрачными элементами
            ignore_opacity    = true,  -- ДОБАВЛЕННАЯ СТРОКА: размытие игнорирует прозрачность окна
        },    },

    -- ───────── Разное и Экосистема (Misc & Ecosystem) ─────────
    misc = {
        font_family              = "JetBrains Mono",
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
        force_default_wallpaper  = 0,
    },

    ecosystem = {
        no_update_news   = true,
        no_donation_nag  = true,
    },

    cursor = {
        no_warps            = true,
        no_hardware_cursors = true, -- Защита от мигания на NVIDIA
        use_cpu_buffer      = true,
    },
})

----------------------------------------------------------------------------------------
---- АНИМАЦИИ И КРИВЫЕ БЕЗЬЕ (ANIMATIONS) -----------------------------------------------
----------------------------------------------------------------------------------------

hl.config({ animations = { enabled = true } })

-- Регистрация ваших кастомных кривых Безье (точки x1, y1, x2, y2 переведены в таблицы параметров)
hl.curve("fluentIn",      { type = "bezier", points = { {0.05, 0.9},  {0.1, 1.0}  } })
hl.curve("fluentOut",     { type = "bezier", points = { {0.3, 0},     {0.8, 0.15} } })
hl.curve("layerCurveIn",  { type = "bezier", points = { {0.1, 0.9},  {0.2, 1.0}  } })
hl.curve("wsSmooth",      { type = "bezier", points = { {0.25, 1},    {0.2, 1}    } })
hl.curve("moveSmooth",    { type = "bezier", points = { {0.15, 0.85}, {0.1, 1.0}  } })
hl.curve("wsBounce",      { type = "bezier", points = { {0.18, 1.15}, {0.32, 1.0} } })

-- Применение анимаций к элементам интерфейса согласно вашим скоростям
hl.animation({ leaf = "windows",       enabled = true, speed = 7,  bezier = "fluentIn",     style = "popin 1%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 6,  bezier = "fluentOut",    style = "popin 60%" })
hl.animation({ leaf = "windowsMove",   enabled = true, speed = 12, bezier = "moveSmooth" })
hl.animation({ leaf = "layers",        enabled = true, speed = 6,  bezier = "layerCurveIn", style = "fade" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 6,  bezier = "layerCurveIn", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 5,  bezier = "fluentOut",    style = "fade" })
hl.animation({ leaf = "fade",          enabled = true, speed = 6,  bezier = "layerCurveIn" })

-- Анимация воркспейсов (Эффект перелистывания с пружиной смартфона)
hl.animation({ leaf = "workspaces",    enabled = true, speed = 8,  bezier = "wsBounce",     style = "slide" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 8,  bezier = "wsBounce",     style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 8,  bezier = "wsBounce",     style = "slide" })
-- Кривая (плавный старт, мягкое дотягивание в конце)
hl.curve("fluentIn", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.0} } })


----------------------------------------------------------------------------------------
---- ПОВЕДЕНИЕ ЛАЙАУТОВ (LAYOUTS) ------------------------------------------------------
----------------------------------------------------------------------------------------

hl.config({
    dwindle = {
        preserve_split = true,
    },
    master = {
        new_status = "master",
    },
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        -- ИСПРАВЛЕНИЕ: Включаем две раскладки (американскую и русскую)
        kb_layout  = "us,ru",
        kb_variant = "",
        kb_model   = "",
        -- ИСПРАВЛЕНИЕ: Задаем комбинацию клавиш для переключения раскладки
        kb_options = "grp:win_space_toggle",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

----------------------------------------------------------------------------------------
---- KEYBINDINGS (STRICT LUA FIX) -----------------------------------------------------
----------------------------------------------------------------------------------------

local mainMod = "SUPER"

-- ───────── Мышиные события (Mouse Binds) ─────────
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag,   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize, { mouse = true })

-- ───────── Основные действия с окнами ─────────
-- ИСПРАВЛЕНИЕ: Добавлен пустой объект параметров для закрытия окон
hl.bind(mainMod .. " + C",         hl.dsp.window.close({})) 
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + F",         hl.dsp.window.fullscreen({ mode = 0 }))

-- Перемещение окон (Move Window)
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }),  { repeating = true })
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }),    { repeating = true })
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }),  { repeating = true })

-- Изменение размера окон (Resize Active)
hl.bind(mainMod .. " + CTRL + left",  hl.dsp.window.resize({ x = -200, y = 0, relative = true }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.resize({ x = 200, y = 0, relative = true }))
hl.bind(mainMod .. " + CTRL + up",    hl.dsp.window.resize({ x = 0, y = -200, relative = true }))
hl.bind(mainMod .. " + CTRL + down",  hl.dsp.window.resize({ x = 0, y = 200, relative = true }))

-- Переключение фокуса (Focus)
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- ───────── Запуск приложений и IPC Noctalia v5 ─────────
hl.bind("CTRL + ALT + T", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("nautilus"))

-- ИСПРАВЛЕНИЕ: Нативные вызовы переключателей модулей Noctalia v5 через exec_cmd
hl.bind(mainMod .. " + R", function() hl.exec_cmd("noctalia msg panel-toggle launcher") end)
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("noctalia toggle clipboard"))
hl.bind(mainMod .. " + P",         hl.dsp.exec_cmd("noctalia toggle control-center"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("noctalia toggle settings"))
hl.bind(mainMod .. " + Q",         hl.dsp.exec_cmd("noctalia toggle media"))
hl.bind(mainMod .. " + B",         hl.dsp.exec_cmd("noctalia toggle power"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("noctalia toggle wallpaper"))
hl.bind(mainMod .. " + S",         hl.dsp.exec_cmd("noctalia toggle calendar"))
hl.bind(mainMod .. " + N",         hl.dsp.exec_cmd("noctalia toggle network"))
hl.bind(mainMod .. " + V",         hl.dsp.exec_cmd("noctalia toggle volume"))
hl.bind(mainMod .. " + H",         hl.dsp.exec_cmd("noctalia toggle guide"))

-- Скриншоты и системные утилиты
hl.bind("Print",                 hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh"),          { locked = true })
hl.bind("SHIFT + Print",         hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh --edit"),   { locked = true })
hl.bind(mainMod .. " + Print",         hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh --full"),   { locked = true })
hl.bind(mainMod .. " + SHIFT + Print", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh --full --edit"), { locked = true })

-- Блокировка экрана и Управление медиаплеером
hl.bind("XF86PowerOff",   hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/lock.sh"), { locked = true })
hl.bind(mainMod .. " + L",      hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/lock.sh"), { locked = true, repeating = true })
hl.bind(mainMod .. " + SPACE",  hl.dsp.exec_cmd("playerctl play-pause"),                { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"),                { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"),                { locked = true })

-- Мультимедиа клавиши (Громкость и Яркость)
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),   { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true })
hl.bind("Caps_Lock",            hl.dsp.exec_cmd("sleep 0.1"),                                      { locked = true })

-- Циклический перебор активных мониторов
hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd("~/.config/hypr/scripts/focus_next_monitor.sh"))

-- ───────── Рабочие столы (Workspaces 1-10) ─────────
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

----------------------------------------------------------------------------------------
---- WINDOW & LAYER RULES (NATIVE LUA SYNTAX) ------------------------------------------
----------------------------------------------------------------------------------------

-- Игнорирование запросов на максимизацию от приложений
local suppressMaximizeRule = hl.window_rule({
    name  = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

-- Исправление проблем с перетаскиванием в XWayland
hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },
    no_focus = true,
})

-- Фикс позиции для утилиты hyprland-run
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },
    move  = "20 monitor_h-120",
    float = true,
})

-- ───────── Правила для окон (Window Rules) ─────────

-- Настройки для встроенного меню приложений (App Launcher) Noctalia v5
hl.window_rule({
    name  = "noctalia-launcher",
    match = { title = "^(app-launcher)$" },
    float = true,
    center = true,
    size  = "1200 600",
    animation = "slide",
})

-- Настройка прозрачности для терминала Kitty (0.85 override)
hl.window_rule({
    name  = "kitty-opacity",
    match = { class = "^(kitty)$" },
    opacity = "0.85 override 0.85 override",
})

-- ───────── Правила для слоев (Layer Rules) ─────────

-- Отключаем анимацию для всплывающих OSD индикаторов Noctalia и системы
hl.layer_rule({
    name  = "no-anim-volume-osd",
    match = { namespace = "^(volume_osd)$" },
    no_anim = true,
})

hl.layer_rule({
    name  = "no-anim-brightness-osd",
    match = { namespace = "^(brightness_osd)$" },
    no_anim = true,
})

-- Отключаем анимацию для утилиты выбора цвета hyprpicker
hl.layer_rule({
    name  = "no-anim-hyprpicker",
    match = { namespace = "hyprpicker" },
    no_anim = true,
})

-- Включаем размытие фона и прозрачность для экрана блокировки (ext-session-lock)
hl.layer_rule({
    name  = "blur-lockscreen",
    match = { namespace = "ext-session-lock" },
    blur  = true,
    ignore_alpha = 0.2,
})

----------------------------------------------------------------------------------------
---- ФИНАЛЬНЫЙ ФИКС ЗАВИСАНИЯ БЛЮРА ДЛЯ NOCTALIA V5 (БЕЗ ОШИБОК) -------------------------
----------------------------------------------------------------------------------------

-- Исправление для слоя OSD / Строки ввода (Убирает заблюренный квадрат)
hl.layer_rule({
    name  = "noctalia-osd-blur-fix",
    match = { namespace = "^(noctalia-osd)$" }, -- Чётко ловим проблемный оверлей
    
    -- Мгновенно скрываем слой и ломаем под ним системный блюр Hyprland
    no_anim = false,
    ignore_alpha = 1.0, 
})

-- Исправление для слоя панели задач
hl.layer_rule({
    name  = "noctalia-bar-blur-fix",
    match = { namespace = "^(noctalia-bar-default)$" },
    no_anim = false,
})

-- For Noctalia Color templates
require("noctalia").apply_theme()
hl.window_rule({
    name    = "vscode-blur",
    match   = { class = "^(code|code-url-handler)$" },
    opacity = "0.85 override 0.85 override", -- Прозрачность автоматически вызовет блюр композитора
})
