font_family      JetBrains Mono
font_size        13
bold_font        auto
italic_font      auto
bold_italic_font auto

cursor_trail 1

background_opacity 0.5
confirm_os_window_close 0

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no
hide_window_decorations yes

window_padding_width 4

include ~/.config/kitty/kitty-matugen-colors.conf


# Отключаем размытие внутри самого Kitty (чтобы не дублировать работу Hyprland)
background_blur 0

# ─────────────────────────────
# Горячие клавиши (Clipboard)
# ─────────────────────────────

# Копирование: если текст выделен — копирует, если нет — работает как прерывание (SIGINT)
map ctrl+c copy_and_clear_or_interrupt

# Вставка скопированного текста из буфера обмена
map ctrl+v paste_from_clipboard
# Запуск кастомной функции Zsh при старте, после чего переключение в обычный режим
# Идеальный автозапуск после полной инициализации Zsh
